const FarmEvent = require('../models/FarmEvent');
const { computeGrowthStatus } = require('./cropKnowledge');

async function generateCropCalendar(farmerId, deviceId, cropType, plantingDate) {
  // Clear out any previously auto-generated events for this farmer's device —
  // this handles the case where a farmer changes their crop mid-season.
  // Events the farmer added manually (autoGenerated: false) are untouched.
  await FarmEvent.deleteMany({ farmerId, deviceId, autoGenerated: true });

  const status = computeGrowthStatus(cropType, plantingDate);
  const planted = new Date(plantingDate);
  const events = [];

  // Sowing event, marking day zero
  events.push({
    farmerId, deviceId, autoGenerated: true,
    title: `Sowing — ${cropType}`,
    type: 'sowing',
    eventDate: planted,
    notes: `Planted on this date. Expected duration: ${status.durationDays} days.`
  });

  // Two fertilizing checkpoints — roughly at 20% and 55% of the growth cycle,
  // common simplified timing for basal + top-dress application
  const fert1 = new Date(planted);
  fert1.setDate(fert1.getDate() + Math.round(status.durationDays * 0.20));
  events.push({
    farmerId, deviceId, autoGenerated: true,
    title: 'Fertilizer application (early stage)',
    type: 'fertilizing',
    eventDate: fert1,
    notes: 'Suggested basal/early fertilizer stage — confirm exact dosage with local agricultural officer.'
  });

  const fert2 = new Date(planted);
  fert2.setDate(fert2.getDate() + Math.round(status.durationDays * 0.55));
  events.push({
    farmerId, deviceId, autoGenerated: true,
    title: 'Fertilizer application (mid stage)',
    type: 'fertilizing',
    eventDate: fert2,
    notes: 'Suggested top-dress fertilizer stage — confirm exact dosage with local agricultural officer.'
  });

  // Irrigation check reminders, roughly every 2 weeks through the growth cycle
  const numChecks = Math.max(1, Math.floor(status.durationDays / 14));
  for (let i = 1; i <= numChecks; i++) {
    const checkDate = new Date(planted);
    checkDate.setDate(checkDate.getDate() + i * 14);
    if (checkDate < status.harvestDate) {
      events.push({
        farmerId, deviceId, autoGenerated: true,
        title: 'Irrigation system check',
        type: 'irrigation_check',
        eventDate: checkDate,
        notes: 'Routine check — confirm sensors and pump are working correctly.'
      });
    }
  }

  // Harvest event
  events.push({
    farmerId, deviceId, autoGenerated: true,
    title: `Expected harvest — ${cropType}`,
    type: 'harvest',
    eventDate: status.harvestDate,
    notes: `Based on a typical ${status.durationDays}-day growth cycle for this crop.`
  });

  await FarmEvent.insertMany(events);
  return events;
}

module.exports = { generateCropCalendar };